### PR TITLE
NameAdded

### PR DESCRIPTION
**Pull request by shubhBindal**

### CODE REVIEW

**Comment by RohanKumar01** [comment]
Hey @shbd845 ,
Your branch has some conflicts  with the main branch. Please fix it and then send a PR again.

**Comment by shubhBindal** [comment]
hello @RohanKumar01, i have resolved the issue.
Actually ig it happened because instead of creating a new branch i committed to main and changes made after me were merged first.
So there were conflicts.
Please merge this PR first before any other otherwise it might happen again.
Thanks

**Comment by shubhBindal** [comment]
Please add "hactoberfest-accepted" label to this PR.

**Comment by RohanKumar01** [comment]
Hey @shbd845 , 

I tried merging your PR but it still shows some issue. 
I'm closing this PR. Please, Send a new one

**Pull request closed without merging**
